name: Test
on:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start PostgreSQL
        run: |
          docker run -d -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=postgres postgres:13.3

      - name: Install dependencies
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
        run: |
          npm install
          npx prisma db push
          npx prisma generate

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/typevocab
        run: |
          npm run test

      - name: Merge to main
        if: ${{ success() && github.event_name == 'pull_request' && github.actor == 'leemhoon00' }}
        uses: hmarr/auto-approve-action@v3
